[package]
name = "blocklistdownloadthing"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
serde = { version = "1.0.123", features = ["derive"] }
ureq = "2.0.2"
eyre = "0.6.5"
url = { version = "2.2.1", features = ["serde"] }
once_cell = "1.7.0"
regex = "1.4.3"
atomicwrites = "0.2.5"
serde_json = "1.0.63"
log = "0.4.14"
env_logger = "0.8.3"
