[package]
name = "blocklistdownloadthing"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.0.14", features = ["derive"] }
serde = { version = "1.0.136", features = ["derive"] }
ureq = "2.4.0"
eyre = "0.6.6"
url = { version = "2.2.2", features = ["serde"] }
once_cell = "1.9.0"
regex = "1.5.4"
atomicwrites = "0.3.1"
serde_json = "1.0.78"
log = "0.4.14"
env_logger = "0.9.0"
