[package]
name = "blocklistdownloadthing"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
serde = { version = "1.0.116", features = ["derive"] }
ureq = "1.4.1"
eyre = "0.6.0"
url = { version = "2.1.1", features = ["serde"] }
once_cell = "1.4.1"
regex = "1.3.9"
atomicwrites = "0.2.5"
serde_json = "1.0.57"
